spring:
  application:
    name: config-server-local
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /data/spring-cloud-demo/config

server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true # 表示访问路径显示IP地址