server:
  port: 4001
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true # 表示访问路径显示IP地址

zuul:
  routes: #配置映射
    service-api: # 一个模块配置映射规则
        serviceId: service-api #此处的别名表示的将真实的微服务名称起一个别名,之后就可以通过别名来访问
        path: /zuul-api/**  #表示此配置映射哪些restfull API地址
        retryable: true # 是否重试
    service-ribbon: # 一个模块配置映射规则
        serviceId: service-ribbon #此处的别名表示的将真实的微服务名称起一个别名,之后就可以通过别名来访问
        path: /zuul-ribbon/** #表示此配置映射哪些restfull API地址
    service-feign: # 一个模块配置映射规则
        serviceId: service-feign #此处的别名表示的将真实的微服务名称起一个别名,之后就可以通过别名来访问
        path: /zuul-feign/** #表示此配置映射哪些restfull API地址
        retryable: true # 是否重试