server:
  port: 6001
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url:  http://localhost:5001 # server-zipkin的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true # 表示访问路径显示IP地址